name: Node CI

on:
  workflow_dispatch:
  push:
  schedule:
    # UTC 表記
    # 日本時間 毎日08:11
    - cron: '11 17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm test
